### ISSUE TITLE
Track names in Chapterization over Overdrive files should not include the book name

### ISSUE THREAD

**Issue by tmchow** [rmcrackan/inAudible#5]
I have overdrive files, and trying to chapterize them. It all works fine but there is one issue where "track name" in ID3 tag has more than just the chapter name. It contains the book name as well. 

So if the book name was say "Hello World" and the chapter name was "Chapter 1" the ID3 track name is set to something like `Hello World - 001 - Chapter 1`.  Instead it should be `Chapter 1`.

I would've tried to submit a PR but there's no source code :(

**Comment by rmcrackan** [comment]
Sorry, I didn't create inAudible and I don't provide support. It's available here for download as a courtesy because some people don't feel good about getting it from torrent sites. The author gave me permission to host the installers here. Frankly it's incredibly outdated (latest is Aug 12 2017). I recommend other [more recent software](https://github.com/rmcrackan/AudiobookHub#backup-decrypt-convert-organize)
