### ISSUE TITLE
how to get and install inAuddible-NG-keys pacakge. 

### ISSUE THREAD

**Issue by rogergithubbing** [rmcrackan/inAudible#7]
Hi,

When I try to process a file, I get this message; How can I fix that ? Thanks !

Could not find your key. You can probably fix this problem by downloading and installing the inAuddible-NG-keys pacakge. You can likely find this package from the same place that you found inAudible.

**Comment by rmcrackan** [comment]
Sorry, I didn't create inAudible and I don't provide support. It's available here for download as a courtesy because some people don't feel good about getting it from torrent sites. The author gave me permission to host the installers here. Frankly it's incredibly outdated (latest is Aug 12 2017). I recommend other [more recent software](https://github.com/rmcrackan/AudiobookHub#backup-decrypt-convert-organize)
